### ISSUE TITLE
java.lang.OutOfMemoryError when running a test

### ISSUE THREAD

**Issue by thachlp** [instancio/instancio#428]
I first try to use instancio, so please help.
**Describe the bug**
When I try to create my object, I see an endless this line until the test fail by OutOfMemoryError
```
DEBUG org.instancio.internal.nodes.NodeFactory - Created superclass type map: {E=}
```

Stacktrace:
```
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.instancio.internal.util.Verify$$Lambda$344/0x0000000800342840.get$Lambda(Unknown Source)
	at java.base/java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(DirectMethodHandle$Holder)
	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000800064840.linkToTargetMethod(LambdaForm$MH)
	at org.instancio.internal.util.Verify.notNull(Verify.java:27)
	at org.instancio.internal.util.TypeUtils.getRawType(TypeUtils.java:61)
	at org.instancio.internal.nodes.NodeFactory.createNodeWithSubtypeMapping(NodeFactory.java:134)
	at org.instancio.internal.nodes.NodeFactory.fromClass(NodeFactory.java:178)
	at org.instancio.internal.nodes.NodeFactory.createNode(NodeFactory.java:76)
	at org.instancio.internal.nodes.NodeFactory.lambda$createChildrenFromFields$2(NodeFactory.java:303)
	at org.instancio.internal.nodes.NodeFactory$$Lambda$391/0x0000000800367440.apply(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.instancio.internal.nodes.NodeFactory.createChildrenFromFields(NodeFactory.java:305)
	at org.instancio.internal.nodes.NodeFactory.fromClass(NodeFactory.java:199)
	at org.instancio.internal.nodes.NodeFactory.createNode(NodeFactory.java:76)
	at org.instancio.internal.nodes.NodeFactory.lambda$createContainerNodeChildren$1(NodeFactory.java:295)
	at org.instancio.internal.nodes.NodeFactory$$Lambda$393/0x0000000800366c40.apply(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.instancio.internal.nodes.NodeFactory.createContainerNodeChildren(NodeFactory.java:297)
	at org.instancio.internal.nodes.NodeFactory.fromParameterizedType(NodeFactory.java:221)
	at org.instancio.internal.nodes.NodeFactory.createNode(NodeFactory.java:78)
```

**Sample code reproducing the issue**
```java
 User user1 = Instancio.create(User.class);
```

- Instancio version: 2.8

**Comment by armandino** [comment]
@thachlp, thanks for reporting this. Could you please also provide the `User` class so I can reproduce the issue?

**Comment by thachlp** [comment]
> @thachlp, thanks for reporting this. Could you please also provide the `User` class so I can reproduce the issue?

Thanks for answering me, @armandino.
This class is an entity class, It references another class, and another class refers to another, etc.. let's see the references chart, hope it helps. 
I think it's caused the infinite loop on creating objects, from my side, I only need to create an User object, don't really need a reference object.


![User references](https://user-images.githubusercontent.com/11583408/218764111-0db91ddb-5f6d-42b3-8048-2a6d822c60e9.png)

**Comment by armandino** [comment]
@thachlp, do you have the sources available on GitHub? If not, if you can provide a minimal sample (removing any irrelevant classes) that would be great.

**Comment by armandino** [comment]
@thachlp, can you try version 2.9.0 and see if you still get the error?

**Comment by thachlp** [comment]
> @thachlp, can you try version 2.9.0 and see if you still get the error?
Perfect! It works as expected. Thank you for your support <3

**Comment by thachlp** [comment]
The problem was resolved on version 2.9.0

**Comment by armandino** [comment]
@thachlp thanks very much for confirming! :) I'm glad to hear it. I will try to make more performance improvements for the next release.

Let me know if you run into any other problems.

**Comment by thachlp** [comment]
> @thachlp thanks very much for confirming! :) I'm glad to hear it. I will try to make more performance improvements for the next release.
> 
> Let me know if you run into any other problems.


Thanks for your patient support, In recent days, I have had some other stuff so I only can be back today and you resolve it ^.^
Your project is really helpful! 🚀
