### ISSUE TITLE
Improve exception handling

### ISSUE THREAD

**Issue by grubeninspekteur** [instancio/instancio#694]
### Feature description

By default, the [`org.instancio.internal.util.ExceptionHandler`](https://github.com/instancio/instancio/blob/c60514bfdc8a2c31fd9c2f61a3a5124b02f7bead/instancio-core/src/main/java/org/instancio/internal/util/ExceptionHandler.java#L46) logs exceptions during instance creation on DEBUG level and a `null` instance is returned. I have registered a custom generator via the SPI that threw an exception:

```
Caused by: java.lang.UnsupportedOperationException: Please implement the randomizer for class XYZ
	at com.example.project(ExampleGeneratorProvider.java:25)
	at org.instancio.internal.generator.GeneratorProviderFacade.resolveViaNewSPI(GeneratorProviderFacade.java:93)
	at org.instancio.internal.generator.GeneratorProviderFacade.getGenerator(GeneratorProviderFacade.java:66)
	at org.instancio.internal.generator.GeneratorResolver.get(GeneratorResolver.java:67)
	at org.instancio.internal.handlers.UsingGeneratorResolverHandler.getResult(UsingGeneratorResolverHandler.java:54)
	at org.instancio.internal.GeneratorFacade.generateNodeValue(GeneratorFacade.java:103)
	at org.instancio.internal.InstancioEngine.generateValue(InstancioEngine.java:508)
	at org.instancio.internal.InstancioEngine.generatePojo(InstancioEngine.java:174)
	at org.instancio.internal.InstancioEngine.createObject(InstancioEngine.java:120)
	at org.instancio.internal.InstancioEngine.populateChildren(InstancioEngine.java:485)
	at org.instancio.internal.InstancioEngine.generatePojo(InstancioEngine.java:176)
	at org.instancio.internal.InstancioEngine.createObject(InstancioEngine.java:120)
	at org.instancio.internal.InstancioEngine.createObject(InstancioEngine.java:504)
	at org.instancio.internal.InstancioEngine.generateCollection(InstancioEngine.java:376)
	at org.instancio.internal.InstancioEngine.createObject(InstancioEngine.java:112)
	at org.instancio.internal.InstancioEngine.populateChildren(InstancioEngine.java:485)
	at org.instancio.internal.InstancioEngine.generatePojo(InstancioEngine.java:176)
	at org.instancio.internal.InstancioEngine.createObject(InstancioEngine.java:120)
	at org.instancio.internal.InstancioEngine.lambda$createRootObject$0(InstancioEngine.java:96)
	at org.instancio.internal.util.ExceptionHandler.conditionalFailOnError(ExceptionHandler.java:42)
```

It was difficult to debug this problem since we have only INFO level logging enabled. Though even with DEBUG enabled, the logged message does not contain the stack trace, so it is not easy to spot when you're used to scanning logs for stack traces.

I'd like to suggest the following improvements:

* Supply the throwable to LOG.debug as the last parameter instead of its name and message, this way Log4j should log the stack trace as well
* Remove or adjust the message "Please submit a bug report including the stacktrace" since the exception could also come from user provided generators
* make the "instancio.failOnError" system property also configurable inside the "instancio.properties" file. It is easy to forget supplying the system parameter when running tests from the IDE
* consider making "failOnError=true" the default. While this is a breaking change, it would help to detect bugs earlier, both in user and library code

**Comment by armandino** [comment]
@grubeninspekteur thanks for reporting this issue and also the suggestions. I've been working on improving error handling and various error messages lately, so I appreciate the feedback. I will look into this.

**Comment by armandino** [comment]
@grubeninspekteur version `3.0.1` should be available from Maven central now. It includes a new setting `Keys.FAIL_ON_ERROR` which can be configured globally in `instancio.properties`:

```
fail.on.error=true
```

Thanks for making the suggestion. I think it's a great idea! It's disabled by default though to avoid breaking changes.



I also added a Troubleshooting section to the user guide: https://www.instancio.org/user-guide/#troubleshooting

If you run into any other issues, please let me know.

**Comment by grubeninspekteur** [comment]
Thank you very much, and also for https://github.com/instancio/instancio/pull/696 !
