### ISSUE TITLE
How to use nullable choices with `oneOf`?

### ISSUE THREAD

**Issue by f4lco** [instancio/instancio#719]
**Describe the bug**

Because the `oneOf` generator does not support `nullable()`, I went on to explore ways to use `oneOf` with `null`.

The **feature** request part of this ticket is probably about adding `nullable()` to the `oneOf` generator.

The **bug** part of this ticket concers inconsistency between `oneOf(T... choices)`, which supports null values, and `oneOf(Collection<T> choices)`, which throws an exception.

**Expected result**

The following methods behave identically with regard to null values:
- `oneOf(T... choices)`
- `oneOf(Collection<T> choices)`

which removes surprising behavior from Instancio, because we can convert between array and collection of choices without a change in behavior.

**Actual result**

- `oneOf(T... choices)` works as expected per user perspective for `oneOf(null)`
- `oneOf(Collection<T> choices)` may throw an exception when the choices contain null

````
Error creating an object
 -> at redacted.testdata.InstancioTest.nullableWithOneOf(InstancioTest.kt:30)

Reason: exception thrown by a custom Generator or Supplier

 -> Could not generate value for: field InstancioTest$nullableWithOneOf$Person.age (depth=1)

    <1:InstancioTest$nullableWithOneOf$Person: Integer age>
     └──<0:InstancioTest$nullableWithOneOf$Person>


org.instancio.exception.InstancioApiException: 

Error creating an object
 -> at redacted.testdata.InstancioTest.nullableWithOneOf(InstancioTest.kt:30)

Reason: exception thrown by a custom Generator or Supplier

 -> Could not generate value for: field InstancioTest$nullableWithOneOf$Person.age (depth=1)

    <1:InstancioTest$nullableWithOneOf$Person: Integer age>
     └──<0:InstancioTest$nullableWithOneOf$Person>


	at app//org.instancio.internal.util.Fail.withUsageError(Fail.java:73)
	at app//org.instancio.internal.GeneratorFacade.generateNodeValue(GeneratorFacade.java:113)
	at app//org.instancio.internal.InstancioEngine.generateValue(InstancioEngine.java:642)
	at app//org.instancio.internal.InstancioEngine.createObject(InstancioEngine.java:140)
	at app//org.instancio.internal.InstancioEngine.createObject(InstancioEngine.java:170)
	at app//org.instancio.internal.InstancioEngine.populateChildren(InstancioEngine.java:566)
	at app//org.instancio.internal.InstancioEngine.generatePojo(InstancioEngine.java:177)
	at app//org.instancio.internal.InstancioEngine.createObject(InstancioEngine.java:152)
	at app//org.instancio.internal.InstancioEngine.createObject(InstancioEngine.java:170)
	at app//org.instancio.internal.InstancioEngine.lambda$createRootObject$0(InstancioEngine.java:100)
	at app//org.instancio.internal.ErrorHandler.conditionalFailOnError(ErrorHandler.java:65)
	at app//org.instancio.internal.InstancioEngine.createRootObject(InstancioEngine.java:99)
	at app//org.instancio.internal.ApiImpl.create(ApiImpl.java:181)
	at app//redacted.testdata.InstancioTest.nullableWithOneOf(InstancioTest.kt:30)
	at java.base@17.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.7/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.7/java.lang.reflect.Method.invoke(Method.java:568)
	at app//org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
````

**Additional information**
Add any other context about the problem here

**Link to a minimal sample project reproducing the issue or runnable sample code**
```kotlin
@Test
fun nullableWithOneOf() {
    data class Person(val age: Int?)

    // works
    val person1: Person = Instancio.of(Person::class.java).run {

        generate(Select.field("age")) { gen ->
            gen.oneOf(null, 21)
        }

        create()
    }

    // works in 50% of cases
    val person2: Person = Instancio.of(Person::class.java).run {

        generate(Select.field("age")) { gen ->
            gen.oneOf(listOf(null, 21))
        }

        create()
    }


    // works
    val person3: Person = Instancio.of(Person::class.java).run {

        withNullable(Select.field("age"))
        generate(Select.field("age")) { gen ->
            gen.oneOf(listOf(21))
        }

        create()
    }

    // desired?
    val person4: Person = Instancio.of(Person::class.java).run {

        withNullable(Select.field("age"))
        generate(Select.field("age")) { gen ->
            gen.oneOf(listOf(21))/*.nullable()*/
        }

        create()
    }
}
```

- Java version: 17
- Instancio version: 3.0.1

**Comment by armandino** [comment]
@f4lco thanks very much for reporting this bug. I was able to reproduce it based on your example. It will be fixed in the next release.

**Comment by f4lco** [comment]
Thank you so much @armandino for the prompt reply and fix 🥇
