### ISSUE TITLE
Error loading `instancio.properties` containing certain enum values

### ISSUE THREAD

**Issue by CommentSectionScientist** [instancio/instancio#773]
**Describe the bug**
Several settings in the instancio.properties file from the [User Guide](https://www.instancio.org/user-guide/#overriding-settings-using-a-properties-file) are not useable.
So far if found 
- hint.after.generate=POPULATE_NULLS_AND_DEFAULT_PRIMITIVES
- on.set.field.error=IGNORE
- on.set.method.error=ASSIGN_FIELD
- on.set.method.not.found=ASSIGN_FIELD
- ...
not working.

If i copy these to my instancio.properties i get an error:
```
java.lang.ExceptionInInitializerError
	at org.instancio.internal.context.ModelContext.createSettings(ModelContext.java:130)
	at org.instancio.internal.context.ModelContext.<init>(ModelContext.java:102)
	at org.instancio.internal.context.ModelContext$Builder.build(ModelContext.java:404)
	at org.instancio.internal.ApiImpl.createModel(ApiImpl.java:201)
	at org.instancio.internal.ApiImpl.create(ApiImpl.java:180)
	at org.instancio.Instancio.create(Instancio.java:153)
	at org.instancio.internal.settings.SettingsSupportTest.verifyFunctions(SettingsSupportTest.java:31)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.function.Function.apply(Object)" because "fn" is null
	at org.instancio.internal.settings.InternalSettings.convertValueToKeyType(InternalSettings.java:205)
	at org.instancio.internal.settings.InternalSettings.lambda$from$0(InternalSettings.java:80)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
	at java.base/java.util.Properties.forEach(Properties.java:1422)
	at org.instancio.internal.settings.InternalSettings.from(InternalSettings.java:66)
	at org.instancio.settings.Settings.from(Settings.java:84)
	at org.instancio.support.Global.<clinit>(Global.java:31)
	... 10 more
```

Is the properties file from the User Guide outdated? Or should these settings work?

**Expected result**
All Settings from the instancio.properties from the User Guide should be working

**Actual result**
Several Settings in the instancio.properties from the User Guide throw an Error

**Additional information**
Add any other context about the problem here

**Link to a minimal sample project reproducing the issue or runnable sample code**
In SettingsSupportTest.java add following assert:
```java
assertThat(SettingsSupport.getFunction(AfterGenerate.class).apply("POPULATE_ALL")).isEqualTo(AfterGenerate.POPULATE_ALL);
```
The Assertions fails, because no Function is found -> NPE is thrown
(No valueOf Methode provided by SettingsSupport#createValueOfFunctionsMap() for the enum type)

Or just  use one of the Settings from above in the instancio.properties and create an Object through Instancio.

- Java version: 17
- Instancio version: 3.3.1

**Comment by armandino** [comment]
@CommentSectionScientist thank you for reporting this bug. Please try version `3.3.2`. It should be available from Maven central shortly.

**Comment by CommentSectionScientist** [comment]
@armandino it works with 3.4.0
Thanks
