### ISSUE TITLE
BeanValidation support incompatible with custom GeneratorProvider 

### ISSUE THREAD

**Issue by Mobe91** [instancio/instancio#811]
Given:
* Instancio bean validation support is enabled
* The Instancio target type contains an instance field `name` annotated with a bean validation annotation (e.g. `@NotNull`)
* A custom GeneratorProvider using `org.instancio.spi.InstancioServiceProvider` is configured that returns a generator for field `name`

Then the Instancio object creation fails with an exception like

```
Caused by: java.lang.ClassCastException: class org.instancio.internal.generator.misc.GeneratorActionDecorator cannot be cast to class org.instancio.internal.generator.AbstractGenerator (org.instancio.internal.generator.misc.GeneratorActionDecorator and org.instancio.internal.generator.AbstractGenerator are in unnamed module of loader 'app')
	at org.instancio.internal.annotation.AnnotationUtils.setSpecNullableToFalse(AnnotationUtils.java:31)
	at org.instancio.internal.annotation.CommonBeanValidationHandlerMap$NotNullHandler.process(CommonBeanValidationHandlerMap.java:319)
	at org.instancio.internal.annotation.AbstractAnnotationConsumer.consumeAnnotations(AbstractAnnotationConsumer.java:88)
	at org.instancio.internal.annotation.AnnotationGeneratorSpecProcessor.process(AnnotationGeneratorSpecProcessor.java:103)
	at org.instancio.internal.handlers.UsingGeneratorResolverHandler.getResult(UsingGeneratorResolverHandler.java:64)
	at org.instancio.internal.GeneratorFacade.getGeneratorResult(GeneratorFacade.java:131)
	at org.instancio.internal.GeneratorFacade.generateNodeValue(GeneratorFacade.java:90)
	... 111 more
```
Example implementation of the used custom GeneratorProvider:
```java
public class NameGeneratorProvider implements InstancioServiceProvider {
    private final NameGenerator uniqueEmailGenerator = new NameGenerator();

    @Override
    public GeneratorProvider getGeneratorProvider() {
        return (node, generators) -> {
            Field field = node.getField();
            if (isName(field)) {
                return uniqueEmailGenerator;
            }
            return null;
        };
    }

    private static boolean isName(@Nullable Field field) {
        if (field != null) {
            return "name".equals(field.getName());
        }
        return false;
    }

    private static class NameGenerator implements Generator<String> {
        @Override
        public String generate(Random random) {
            return "constantName";
        }
    }
}
```

- Java version: 17
- Instancio version: 3.5.0

**Comment by armandino** [comment]
@Mobe91 good catch! Thanks for reporting it and the sample code. I could reproduce it using your example. Will be fixed in the next release.

**Comment by armandino** [comment]
Done in `3.5.1`.

**Comment by Mobe91** [comment]
Thank you for the quick fix, I appreciate it!
