### ISSUE TITLE
Simple Quickcheck class test not working since 3.7.0 release

### ISSUE THREAD

**Issue by JoseLora** [instancio/instancio#846]
Hi folks.

Since 3.7.0 release, this simple test is not working for me. It works ok on 3.6.0 release:

```java
class InstancioTest {

  @DisplayName("Test that each product has valid price")
  @Property(samples = 50)
  void productPriceIteration(@ForAll("products") final Product p) {
    assertThat(p.getPrice()).isBetween(BigDecimal.ONE, BigDecimal.TEN);
  }

  Arbitrary<Product> products() {
    return Arbitrary.fromStream(Stream.generate(() -> Instancio.of(Product.class)
        .generate(field(Product::getPrice), gen -> gen.math().bigDecimal().range(BigDecimal.ONE, BigDecimal.TEN))
        .create()));
  }

}
```

Error when running test:

```
org.junit.platform.commons.JUnitException: TestEngine with ID 'instancio-quickcheck' failed to discover tests
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:160)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:132)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:78)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:110)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Caused by: org.junit.platform.commons.JUnitException: ClassSelector [className = 'com.inditex.amigafwk.test.instancio.InstancioTest'] resolution failed
	at org.junit.platform.launcher.listeners.discovery.AbortOnFailureLauncherDiscoveryListener.selectorProcessed(AbortOnFailureLauncherDiscoveryListener.java:39)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:103)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:83)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:113)
	at org.instancio.quickcheck.internal.discovery.InstancioQuickcheckDiscoverer.resolveSelectors(InstancioQuickcheckDiscoverer.java:35)
	at org.instancio.quickcheck.engine.InstancioQuickcheckTestEngine.discover(InstancioQuickcheckTestEngine.java:43)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:152)
	... 13 more
Caused by: java.lang.NoSuchMethodError: 'java.util.stream.Stream org.junit.platform.commons.support.ReflectionSupport.streamNestedClasses(java.lang.Class, java.util.function.Predicate)'
	at org.instancio.quickcheck.internal.discovery.ClassSelectorResolver.lambda$toResolution$12(ClassSelectorResolver.java:131)
	at org.junit.platform.engine.support.discovery.SelectorResolver$Match.expand(SelectorResolver.java:667)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$enqueueAdditionalSelectors$1(EngineDiscoveryRequestResolution.java:110)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4853)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4861)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.enqueueAdditionalSelectors(EngineDiscoveryRequestResolution.java:109)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:95)
	... 18 more
```

Am I doing something wrong?

Thanks in advance!

- Instancio version: 3.7.0

**Comment by armandino** [comment]
@JoseLora  thanks for raising this issue.

@reta can you help with this one?

**Comment by reta** [comment]
@armandino yes, sure! looking ...

**Comment by reta** [comment]
@JoseLora could you please share what JUnit 5 version you are using?

**Comment by JoseLora** [comment]
JUnit version (jupiter, jupiter-api, jupiter-engine, jupiter-params): 5.9.3
JUnit platform (platform-commons, platform-engine, platform-launcher): 1.9.3

**Comment by reta** [comment]
This is the issue sadly since Instancio has JUnit 5.10.x baseline and the method in question is only available in JUnit platform 1.10.x

**Comment by armandino** [comment]
Thanks @reta. Sounds like the quickcheck module in 3.7.0 is using a JUnit platform method available since version 1.10.x, while 3.6.0 did not.

I don't think I've mentioned the required JUnit version anywhere. That's my bad. I'll update the docs to include that.

@JoseLora would you be able to upgrade your JUnit dependencies?

**Comment by reta** [comment]
> Thanks @reta. Sounds like the quickcheck module in 3.7.0 is using a JUnit platform method available since version 1.10.x, while 3.6.0 did not.

That is correct, this is by all means not your fault, it is just a nuance of adding a new test engine implementation which becomes more sensitive to version changes. I believe we could also refactor the code to use older JUnit APIs, what do you think?

**Comment by armandino** [comment]
I think we should be able to use any public APIs from the JUnit version declared by the project's poms. Having said that, if there's an easy workaround available, we could refactor the implementation. I'll leave it up to you since you might want to use other 1.10.x APIs in the future :)

In any case, we should probably document the minimum JUnit version to ensure compatibility between minor version releases.

**Comment by JoseLora** [comment]
It would be great if you could refactor to use older JUnit APIs, if not necessary to depend on latest. We use that JUnit version because we follow Spring Boot dependencies (via spring-boot-starter-test 3.1.5 in this case) and you know it's not always easy to upgrade to latest Spring Boot release.

Thanks for your support!

**Comment by reta** [comment]
Here we are folks https://github.com/instancio/instancio/pull/850

**Comment by armandino** [comment]
Thanks @reta. Will publish a release later today.

**Comment by armandino** [comment]
@JoseLora `3.7.1` should be available from Maven central shortly.
